# Generated by Django 3.0.5 on 2020-04-18 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('Component', models.CharField(max_length=100)),
                ('backgroundColor', models.CharField(max_length=100)),
                ('contentTitle', models.CharField(max_length=100)),
                ('buttonPath', models.CharField(max_length=100)),
                ('backgroundImage', models.CharField(max_length=100)),
            ],
        ),
    ]
