# Generated by Django 3.0.5 on 2020-04-15 19:39

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=1000)),
                ('list_of_recipes', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), size=20)),
                ('preperation_time', models.IntegerField()),
                ('picture', models.CharField(max_length=200)),
            ],
        ),
    ]
