# Generated by Django 3.0.5 on 2020-04-24 18:52

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=2000)),
                ('types', models.CharField(max_length=100)),
                ('picture', models.CharField(max_length=100)),
                ('ingredients', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=30)),
                ('preparation', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), size=30)),
            ],
        ),
    ]
